### ISSUE TITLE
Setting KeepSections and DiscardHeadersAndFootersInKeptSections on a source to true throws exception 'Parameter cannot be null'

### ISSUE THREAD

**Issue by catsgotmytongue** [OfficeDev/Open-Xml-PowerTools#120]
`AddReferenceToExistingHeaderOrFooter()` throws exception 'Parameter cannot be null' in the call to `XAttribute`'s Constructor during the `CopyOrCacheHeaderOrFooter()` method with some documents.

Here's a partial stacktrace:
```
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at OpenXmlPowerTools.DocumentBuilder.AddReferenceToExistingHeaderOrFooter(MainDocumentPart mainDocPart, XElement sect, String rId, XName reference, String toType)
   at OpenXmlPowerTools.DocumentBuilder.CopyOrCacheHeaderOrFooter(WordprocessingDocument doc, CachedHeaderFooter[] cachedHeaderFooter, XElement sect, XName referenceXName, String type)
   at OpenXmlPowerTools.DocumentBuilder.BuildDocument(List`1 sources, WordprocessingDocument output)
   at OpenXmlPowerTools.DocumentBuilder.BuildDocument(List`1 sources)
```

The cause seems to be in `CopyOrCacheHeaderOrFooter()` where the `referenceElement` is not really in the section being processed and then tries to get an element from the `CachedHeaderFooter[]` from the parameter and attempts to get the part ref id what turns out to be null.

I'm also wondering why any code should execute around header/footer references (other than removing them) when `DiscardHeadersAndFootersInKeptSections` was explicitly set to true.

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
