### ISSUE TITLE
HtmlToWmlCssParser.cs Parsing Error

### ISSUE THREAD

**Issue by jureles** [OfficeDev/Open-Xml-PowerTools#253]
Hi,

There is a CSS parsing error that occurs in HtmlToWmlCssParser.cs.

The CSS parser throws an exception for the following CSS style:
`border: solid red .5pt`

On the other side the following CSS style string is properly parsed:
`border: solid red 0.5pt`

I would try to  fix this myself, but I haven't seen any grammar file in the project where I could fix this. It seems like the CSS parsing classes are auto generated. Can someone tell me where can I get it and which  parser generator technology is used?

**Comment by nlsdg** [comment]
You didn't provide the exception that happens.
Does the parser exception specify where in the parser the exception occurs? That would the first starting point to find out.
Or run everything under a debugger and you should get the same result.

**Comment by jureles** [comment]
I'm sorry for the latency.

The easiest way to reproduce this exception is to parse the following HTML fragment with the HtmlToWml converter:
`<p style="border: solid red .5pt;">QQQ</p>`

The error message is: "CssParser error: line 1 col 22: invalid identity"

And the stack trace is:
at OpenXmlPowerTools.HtmlToWml.CSS.Errors.SyntaxError(Int32 line, Int32 col, Int32 n) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 3712
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.SyntaxErr(Int32 n) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 2231
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.Identity(String& ident) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 2821
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.Term(CssTerm& trm) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 3317
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.Exprsn(CssExpression& exp) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 2857
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.Declaration(CssDeclaration& dec) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 2894
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.RuleSet(CssRuleSet& rset) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 2395
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.Css3() in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 2336
   at OpenXmlPowerTools.HtmlToWml.CSS.Parser.Parse() in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 3480
   at OpenXmlPowerTools.HtmlToWml.CSS.CssParser.ParseStream(Stream stream) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 1935
   at OpenXmlPowerTools.HtmlToWml.CSS.CssParser.ParseText(String content) in D:\Projects\MyProject\Loading.Html\OpenXmlPowerTools\HtmlToWmlCssParser.cs:line 1921


Once again, if I instead run the converter with:
`<p style="border: solid red 0.5pt;">QQQ</p>`
... the conversion/parsing suceeds. Notice the change from ".5" -> "0.5".

I hope this helps. Let me know if this helps.

Thanks,
Jure

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
