### ISSUE TITLE
HtmlToWmlConverter fails on embedded images

### ISSUE THREAD

**Issue by bill-long** [OfficeDev/Open-Xml-PowerTools#35]
If the HTML contains an element such as:

```
<img width="125" height="119" alt="cid:image002.jpg@01D08291.F37A1F00" src="data:image/png;base64,/9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAgGBgcGBQg ...
```

It tries to instantiate a Bitmap using that **src** value as a file name, which fails:

```
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
</ExceptionMessage>
<ExceptionType>System.IO.PathTooLongException</ExceptionType>
<StackTrace>
at System.IO.PathHelper.GetFullPathName() at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
 at System.IO.Path.GetFullPathInternal(String path) at System.IO.Path.GetFullPath(String path)
 at System.Drawing.IntSecurity.UnsafeGetFullPath(String fileName)
 at System.Drawing.IntSecurity.DemandReadFileIO(String fileName)
 at System.Drawing.Bitmap..ctor(String filename)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.TransformImageToWml(XElement element, HtmlToWmlConverterSettings settings, WordprocessingDocument wDoc)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.Transform(XNode node, HtmlToWmlConverterSettings settings, WordprocessingDocument wDoc, NextExpected nextExpected, Boolean preserveWhiteSpace)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.<>c__DisplayClass93.<Transform>b__75(XNode n)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.Transform(XNode node, HtmlToWmlConverterSettings settings, WordprocessingDocument wDoc, NextExpected nextExpected, Boolean preserveWhiteSpace)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.<>c__DisplayClassa5.<GenerateNextExpected>b__a1(XNode n)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.GenerateNextExpected(XNode node, HtmlToWmlConverterSettings settings, WordprocessingDocument wDoc, String styleName, NextExpected nextExpected, Boolean preserveWhiteSpace)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.Transform(XNode node, HtmlToWmlConverterSettings settings, WordprocessingDocument wDoc, NextExpected nextExpected, Boolean preserveWhiteSpace)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.<>c__DisplayClass93.<Transform>b__5a(XNode n)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.UpdateMainDocumentPart(WordprocessingDocument wDoc, XElement html, HtmlToWmlConverterSettings settings)
 at OpenXmlPowerTools.HtmlToWml.HtmlToWmlConverterCore.ConvertHtmlToWml(String defaultCss, String authorCss, String userCss, XElement xhtml, HtmlToWmlConverterSettings settings, WmlDocument emptyDocument, String annotatedHtmlDumpFileName) 
```

Since I am performing these conversions inside an IIS app pool, it would be nice to remove the file system calls entirely and transform a MemoryStream instead of creating a file somewhere.

**Comment by EricWhiteDev** [comment]
I've just added support for this.  Just committed to vNext branch.

I also added Xunit tests for this.  Also added a new WmlToHtmlConverter.cs example that converts to HTML putting images in base64 in the src attribute.

I will take a look and see if there is anywhere else that requires a file rather than a MemoryStream.
