### ISSUE TITLE
Save IEnumerable<object> as *.xlsx using a stream approach due to large number of records.

### ISSUE THREAD

**Issue by CleanCodeDeveloper** [OfficeDev/Open-Xml-PowerTools#58]
Hello,
First, i want to thank you Eric White and all the other developers for the hard work and also for sharing it with others!

I would like to request a method where i can pass in an arbitrary `IEnumerable<T>` and a file path. The method should create a spreadsheet using a (true) streaming approach. I already had a look into your Screencast (Using Open XML and LINQ to XML in a Streaming Fashion to Create Huge Spreadsheets) and I tried to build the an Export Function like you pointed out in your `SpreadsheetWriter` Example but I still get the famous `System.OutOfMemoryException`. Furthermore I don’t understand how your approach is different from all the others. You still build up the workbook containing all the data in memory.

A method which reads a few rows and persists them to harddisk without holding everything in memory would be great.

Unfortunately, I don’t know how to do this. Here is my most recent approach based on your `SpreadsheetWriter`. It works fine for small spreadsheets.

Usage:
```C#
List<Tbl_ANALYSIS_MILD_Movements>  testData = Db.Instance.RetrieveMildMovements();
ExcelExport.ExportData<Tbl_ANALYSIS_MILD_Movements>(testData, testData.Count, "Test.xlsx");
```

Source Code:
```C#
using System.Collections.Generic;
using OpenXmlPowerTools;
using System;
using System.Reflection;


namespace ExcelExportTest.ViewModel
{
    public class ExcelExport
    {
        public static void ExportData<T>(IEnumerable<T> data, int totalRows, string destination)
        {
            Type dataType = typeof(T);

            var columnDefinitons = GetColumnDefinitons(dataType);
            var rows = GetRows<T>(columnDefinitons, data, totalRows);

            var worksheetDfn = new WorksheetDfn
            {
                TableName = dataType.Name,
                Name = dataType.Name,
                ColumnHeadings = columnDefinitons,
                Rows = rows
            };

            var workbookDfn = new WorkbookDfn { Worksheets = new[] { worksheetDfn } };

            SpreadsheetWriter.Write(destination, workbookDfn);
        }

        private static List<CellDfn> GetColumnDefinitons(Type dataType)
        {
            List<CellDfn> columnDefinitons = new List<CellDfn>();
            PropertyInfo[] properties = dataType.GetProperties();

            foreach (PropertyInfo column in properties)
            {
                columnDefinitons.Add(new CellDfn()
                {
                    CellDataType = CellDataType.String,
                    Value = column.Name,
                    Bold = true
                });
            }

            return columnDefinitons;
        }

        private static RowDfn[] GetRows<T>(List<CellDfn> columnHeadings, IEnumerable<T> data, int totalRows)
        {
            if (columnHeadings == null) throw new ArgumentNullException();
            if (data == null) throw new ArgumentNullException();

            var dataType = typeof(T);
            PropertyInfo[] properties = dataType.GetProperties();

            var rows = new OpenXmlPowerTools.RowDfn[totalRows];
            var currentRow = 0;
            foreach (var dataEntry in data)
            {
                var currentColumn = 0;
                var row = new OpenXmlPowerTools.RowDfn();

                OpenXmlPowerTools.CellDfn[] cells = new OpenXmlPowerTools.CellDfn[columnHeadings.Count];

                foreach (var column in columnHeadings)
                {
                    var property = dataType.GetProperty(column.Value.ToString());
                    var value = property.GetValue(dataEntry);

                    var tempValue = string.Empty;
                    if (value != null)
                    {
                        tempValue = value.ToString();
                    }

                    cells[currentColumn] = new OpenXmlPowerTools.CellDfn
                    {
                        Value = tempValue,
                        CellDataType = GetOpenXmlExcelType(properties[currentColumn].PropertyType)
                    };

                    currentColumn++;
                }

                row.Cells = cells;

                rows[currentRow] = row;

                currentRow++;
            }

            return rows;
        }

        private static CellDataType GetOpenXmlExcelType(Type type)
        {
            if (type == typeof(short) || type == typeof(short?) ||
                type == typeof(decimal) || type == typeof(decimal?) ||
                type == typeof(double) || type == typeof(double?) ||
                type == typeof(float) || type == typeof(float?) ||
                type == typeof(int) || type == typeof(int?) ||
                type == typeof(long) || type == typeof(long?)) return CellDataType.Number;

            if (type == typeof(bool) || type == typeof(bool?)) return CellDataType.Boolean;
            if (type == typeof(DateTime) || type == typeof(DateTime?)) return CellDataType.Date;

            return CellDataType.String;
        }
    }
}
```
Questions:
- Did i understood your SpreadsheetWriter Example correctly or am i missing the point?
- How can I Improve my code to work with huge collections (700000 Row, 24 Columns)?

Thank you for your advise and keep up the good work!

**Comment by anantu** [comment]
I have faced System.OutOfMemoryException in some of my Open XML code (a bit similar case than you have) when running the 32-bit build, but not getting the exception when running the 64-bit build.

**Comment by EricWhiteDev** [comment]
Hi,

If I remember correctly (it was some years ago when I did that work) the key point is that it is implemented to expect nothing more than something that implements IEnumerable<T>.  So anything that you can provide that is a lazy implementation (write a yield/return iterator), then those items will be short-lived.  I would have to go back and review.

I have assisted other developers in projects of writing spreadsheets in the 100's of thousands of rows. We achieved predictable memory use, a running ~24MB IIRC, so it is possible.  I would not go down the 'huge collections' road, but would focus only on a streaming approach.

-Eric

**Comment by CleanCodeDeveloper** [comment]
Hi,
thank you for your suggestions! Unfortunately, I'm not sure how to change my code to avoid the `System.OutOfMemoryException`. I changed the implementation to `IEnumerable<Tbl_ANALYSIS_MILD_Movements>` on the lowest point i can influence but it does not work. 

```C#
        public IEnumerable<Tbl_ANALYSIS_MILD_Movements> RetrieveMildMovements()
        {
            //Uses Telerik DataAccess ORM for database connection
            //returns IQueryable<Tbl_ANALYSIS_MILD_Movements>
            return this.Connection.Tbl_ANALYSIS_MILD_Movements;

            //Also tried this:
            //return this.Connection.Tbl_ANALYSIS_MILD_Movements.AsEnumerable();
        }
```
Now, the Exceptions occurs in the `SpreadsheetWriter.Write` Method. For the sake of completeness exception is listed below.
```C#
Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.WrappedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Packaging.ZipWrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlRawWriter.WriteValue(String value)
   at System.Xml.XmlWellFormedWriter.WriteValue(String value)
   at OpenXmlPowerTools.SpreadsheetWriter.SerializeRow(SpreadsheetDocument sDoc, XmlWriter xw, Int32 rowCount, RowDfn row, Int32& numColumns)
   at OpenXmlPowerTools.SpreadsheetWriter.SerializeRows(SpreadsheeA first chance exception of type 'System.OutOfMemoryException' occurred in OpenXmlPowerTools.dll
tDocument sDoc, XmlWriter xmlWriter, IEnumerable`1 rows, Int32 startingRowNumber, Int32& numColumns, Int32& numRows)
   at OpenXmlPowerTools.SpreadsheetWriter.AddWorksheet(SpreadsheetDocument sDoc, WorksheetDfn worksheetData)
   at OpenXmlPowerTools.SpreadsheetWriter.Write(String fileName, WorkbookDfn workbook) in mscorlib
 ```


The README.md lists the following feature:
- Writing XLSX files using far simpler code than directly writing the markup, including a streaming approach that enables writing XLSX files with millions of rows.

I would be very grateful if you Eric or someone else could provide a small example how to do so.

**Comment by CarlLanglais** [comment]
Not sure if you found a solution, but this was adapted from the OpenXmlDeveloper.org example, so maybe it'll help you or someone else with this issue now.  The code below output 300K items with 4 fields, which is 1.2M cells of data, to a file in 4.3 seconds.  My memory load went from 42MB, which was data created to a List<T> and put into an IEnumerable<T>, to 108MB by end of SpreadsheetWriter.Write call.  I've run other versions of this export for other collection types on 32 bit and 64 bit servers and user laptops, some with only 2MB of RAM, and exported >2.5M cells of data with no memory issues.

The change to your code is mainly not calling GetRows<T>() before creation of the worksheet, which is throwing all of your rows into memory before attempting to create the worksheet, hence the out of memory.


    // assumes destination exists
    // assumes data always has data, not null or empty
    // test data != null
    // at 'Rows = ', put in a ternary maybe to test data.Any() and insert 1 row that says No Data
    // replace CellDataType.String to use your GetOpenXmlExcelType() method

    public static void ExportTest<T>(IEnumerable<T> data, string destination)
    {
	var dataType = typeof(T);
	var props = typeof(T).GetProperties().Select(x => x.Name).ToList();

	WorkbookDfn workbookDfn = new WorkbookDfn
	{
		Worksheets = new WorksheetDfn[]
		    {
			new WorksheetDfn
			{
				Name = dataType.Name,
				ColumnHeadings =
					props.Select(col => new CellDfn {Value = col.ToString(), Bold = true}),
				Rows = data.Select(row =>
					new RowDfn
					{
						Cells = typeof (T)
							.GetProperties()
							.Select(
								prop =>
									new CellDfn {Value = (prop.GetValue(row) != null ? prop.GetValue(row).ToString() : ""), 
										CellDataType = OpenXmlPowerTools.CellDataType.String })
							})
					}
				}
	};
	
	SpreadsheetWriter.Write(destination, workbookDfn);
}

**Comment by Will-Gregg** [comment]
We recently released v2.71 of the SDK which fixes a memory management problem OfficeDev/Open-XML-SDK#110. This does not address the request for a 'streaming' load/save of content, but may assist in dealing with larger files.

**Comment by CarlLanglais** [comment]
Sorry about missing the stream part.  We are actually trying here ourselves to see if we could get the SpreadsheetWriter.Write() to return a stream instead of void.  

Again sorry for the partial answer.
