### ISSUE TITLE
RevisionAccepter throws Internal error 20, found element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFromRangeStart

### ISSUE THREAD

**Issue by da-web** [OfficeDev/Open-Xml-PowerTools#72]
I have a document with a moveFromRangeStart element and when calling the RevisionAccepter.AcceptRevisions method it give me the following error:
Internal error 20, found element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFromRangeStart,    at OpenXmlPowerTools.RevisionAccepter.<AllParaContentIsDeleted>b__9c(XElement ce)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at OpenXmlPowerTools.RevisionAccepter.AllParaContentIsDeleted(XElement p)
   at OpenXmlPowerTools.RevisionAccepter.<AllContentDeleted>b__9a(BlockContentInfo b)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenXmlPowerTools.RevisionAccepter.AllContentDeleted(IGrouping`2 g)
   at OpenXmlPowerTools.RevisionAccepter.<>c__DisplayClass94.<AcceptDeletedAndMoveFromParagraphMarksTransform>b__8b(IGrouping`2 g, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at OpenXmlPowerTools.RevisionAccepter.AcceptDeletedAndMoveFromParagraphMarksTransform(XNode node)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at OpenXmlPowerTools.RevisionAccepter.AcceptDeletedAndMoveFromParagraphMarksTransform(XNode node)
   at OpenXmlPowerTools.RevisionAccepter.AcceptDeletedAndMoveFromParagraphMarks(XElement element)
   at OpenXmlPowerTools.RevisionAccepter.AcceptRevisionsForPart(OpenXmlPart part)
   at OpenXmlPowerTools.RevisionAccepter.AcceptRevisions(WordprocessingDocument doc)

I took the latest code from master. Basically I found a "fix" but I am not sure whether that is correct (it looks too simple) -> I just added this Tag to the RevisionAccepter.IsRunContent method (returning false).

Can someone please advise or confirm that fix?

Thanks a lot.

**Comment by EricWhiteDev** [comment]
@da-web If you post a sample document that causes RevisionAccepter to throw, I'll take a look at it.
